version: '3'
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"   # Mapea el puerto 8080 del contenedor al puerto 8080 de tu máquina local
    networks:
      - springboot-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_DRIVER_CLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect

networks:
  springboot-network:
    driver: bridge